### PR TITLE
Fixing Backbone sync implementation for the error handler

### PR DESCRIPTION
**Pull request by clemblanco**
The most important thing from this is the second commit fixing the fact that `Alloy.Collections.something.fetch();` without an error callback specified wouldn't trigger the global error handler defined in the RESTe config.

Basically now with:
```javascript
Alloy.Collections.something.fetch({
    error: function() {
        console.log("Local");
    }
})
```
The local handler will be executed.

With:
```javascript
Alloy.Collections.something.fetch();
```
The global error handler from the RESTe config `onError()` will be executed.

Surprisingly `options.error` will always be passed by Backbone even if no `error` is passed from the Backbone call like `fetch()`. See `Backbone.wrapError` from http://docs.appcelerator.com/backbone/0.9.2/docs/backbone.html.

This should also be the case when using Backbone Models instead of Collections.

Some other small tweaks have been pushed too.

### CODE REVIEW

**Comment by jasonkneen** [comment]
I have already fixed the global error issue. Please resolve the conflicts.

**Comment by clemblanco** [comment]
Wait up the retry is not operational here as using the onLoad won't do it for Backbone. I'll review it.

Regards,
Clément Blanco
Web & mobile developer
Cyber-Duck Ltd

**Comment by jasonkneen** [comment]
Leave it with me and I'll take care of it.

**Comment by clemblanco** [comment]
This is what I use at the moment and it's working fine for me.
Feel free to review/reject it but I couldn't find any better way to do it than overriding Backbone wrapError.

**Comment by jasonkneen** [comment]
Still trying to understand the underlying issue here. You want to fire a local error handler if there is one or the global one?

**Comment by clemblanco** [comment]
Basically the initial issue was that `Alloy.Collections.something.fetch();` wouldn't call the global error handler defined in the RESTe config in case of failure.

To me, in case of failure, it should work as follows:
```javascript
// This should trigger the global error handler in the RESTe config.
Alloy.Collections.something.fetch();
```
and
```javascript
// The local error handler defined here should be triggered
// whenever a failure happen instead of the global one.
Alloy.Collections.something.fetch({
    error: function() {
        // local error handler
    }
});
```

But it wasn't. After investigations, it appears that the Backbone function `fetch()` is using a function called `wrapError` in order to wrap any error handler for the `fetch()` function.

See Backbone.Collections `fetch` [definition](http://docs.appcelerator.com/backbone/0.9.2/docs/backbone.html#section-98).

See Backbone `wrapError` [definition](http://docs.appcelerator.com/backbone/0.9.2/docs/backbone.html#section-173).

The `wrapError` function is basically here to wrap all error callbacks and check if a local error callback has been given to the `fetch()` function, if not it will trigger a Backbone event called `error` for the related model.

Because of the `wrapError` function, `options.error` in the previous RESTe version was always defined and was never `null` even though you wouldn't pass a local error callback to the `fetch()` function.

Overriding the `wrapError` was the only clean way I've found to avoid this "always set `options.error` problem" for RESTe.

Apparently `wrapError` has now been removed from the more recent versions of Backbone anyway.

**Comment by jasonkneen** [comment]
I think this should work that if a local error is defined then it's run.

If not a global one is run. Either or. Not both.

Either way I can take care of that without over complicating it.

**Comment by clemblanco** [comment]
> I think this should work that if a local error is defined then it's run.
> If not a global one is run. Either or. Not both.

Yes and this is how it works now.

**Comment by jasonkneen** [comment]
I'm going to close this -- I've taken some elements and added to the latest release (see notes) and fixed error handling and removed the global error passthru (you can do this yourself outside of rest if you like).

Ultimately there were too many commits in this to reconcile easily as the error handling bit was changing a lot and not in the same format as the other error handling going on.

Appreciate the contribution.

**Pull request closed without merging**
